# On Debian, hdparm will also install /etc/rcS.d/hdparm.
# You might want to disable it, to avoid unecessary overhead at boot time.
- name: Install hdparm
  package:
    name: hdparm
    state: present

- name: Copy script
  copy:
    src: hdparm-noapm.sh
    dest: /usr/local/libexec/

- name: Script must be executable
  file:
    path: /usr/local/libexec/hdparm-noapm.sh
    mode: a+rx

- name: Copy systemd service
  copy:
    src: hdparm-noapm.service
    dest: /etc/systemd/system/

- name: Enable systemd service
  systemd:
    daemon_reload: yes
    name: hdparm-noapm.service
    enabled: yes
  register: enable_service

# If the service wasn't already enabled, run the script immediately.
# Don't wait for the next boot/suspend.
- name: Start systemd service
  systemd:
    name: hdparm-noapm.service
    state: started  
  when: enable_service.changed
