# On Debian, hdparm will also install /etc/rcS.d/hdparm.
# You might want to disable it, to avoid unecessary overhead at boot time.
- name: Install hdparm
  package:
    name: hdparm
    state: present

- name: Copy script
  copy:
    src: hdparm-noapm.sh
    dest: /usr/local/libexec/

- name: Script must be executable
  file:
    path: /usr/local/libexec/hdparm-noapm.sh
    mode: a+rx

- name: Copy systemd service
  copy:
    src: hdparm-noapm.service
    dest: /etc/systemd/system/
  register: install_service

- name: Reload systemd service
  systemd:
    daemon_reload: yes
  when: install_service.changed

# "systemd: { enabled: yes }" is too naive.  It appears to believe the
# same "enabled" status shown by `systemctl status`.  However this
# can only be an approximation, since there can be multiple links.
# Ansible 2.5.0, systemd 234.  The following covers the case that bit
# me, though not all cases.
- name: Reset systemd service enabled state
  systemd:
    name: hdparm-noapm.service
    enabled: no
  when: install_service.changed

- name: Enable systemd service
  systemd:
    name: hdparm-noapm.service
    enabled: yes
  register: enable_service

# If the service wasn't already enabled, run the script immediately.
# Don't wait for the next boot/suspend.
- name: Start systemd service
  systemd:
    name: hdparm-noapm.service
    state: started
  when: install_service.changed or enable_service.changed
